import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'he' | 'en';
type Currency = 'ILS' | 'USD';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  setCurrency: (curr: Currency) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  he: {
    'site.title': 'דף אחד',
    'site.tagline': 'כל ספרי ברסלב במקום אחד',
    'nav.home': 'בית',
    'nav.books': 'ספרים',
    'nav.children': 'ערוץ ילדים',
    'nav.women': 'ערוץ נשים',
    'nav.login': 'התחברות',
    'nav.account': 'חשבון',
    'nav.tracking': 'מעקב משלוח',
    'nav.cart': 'עגלה',
    'nav.wishlist': 'רשימת משאלות',
    'nav.admin': 'ניהול',
    'nav.about': 'אודות',
    'nav.contact': 'צור קשר',
    'nav.terms': 'תקנון',
    'search.placeholder': 'חיפוש ספרים, מחבר, קטגוריה...',
    'search.button': 'חיפוש',
    'kav.title': 'קו הזמנות אוטומטי 24/6',
    'kav.phone': '076.598.91.31',
    'categories.all': 'כל הספרים',
    'categories.likutey': 'ליקוטי מוהר"ן',
    'categories.prayer': 'תפילה',
    'categories.stories': 'סיפורי מעשיות',
    'categories.children': 'ילדים',
    'categories.women': 'נשים',
    'featured': 'מוצרים מומלצים',
    'new.arrivals': 'הגיעו לאחרונה',
    'wishlist.title': 'הפריטים ששמרתם',
    'wishlist.subtitle': 'שמרו ספרים מעניינים, חזרו אליהם ולחצו להזמנה בזמן שנוח לכם.',
    'wishlist.empty': 'עוד לא שמרתם פריטים לרשימה',
    'collections': 'אוספים',
    'brands': 'מותגים',
    'recently.viewed': 'נצפו לאחרונה',
    'footer.sitemap': 'מפת האתר',
    'footer.about': 'אודות',
    'footer.contact': 'צור קשר',
    'footer.donations': 'תרומות',
    'footer.policies': 'מדיניות אספקה ופרטיות',
    'footer.terms': 'תקנון האתר',
    'footer.giftcard': 'כרטיס מתנה',
    'footer.balance': 'בדיקת יתרה',
    'footer.rights': '© כל הזכויות שמורות',
    'cart.title': 'עגלה והזמנה',
    'cart.subtitle': 'בדיקת פריטים, שילוח ואמצעי תשלום לפני שליחת ההזמנה.',
    'cart.empty': 'העגלה שלך ריקה כרגע.',
    'cart.continue': 'חזרה לקטלוג',
    'cart.delivery.worldwide': 'משלוחים לכל העולם',
    'cart.delivery.multi': 'מספר אפשרויות אספקה: שליח, דואר, או איסוף עצמי.',
    'cart.items': 'פריטי עגלה',
    'cart.quantity': 'כמות',
    'cart.remove': 'הסר',
    'cart.shipping.worldwide': 'משלוח בינלאומי',
    'cart.shipping.title': 'אפשרויות משלוח',
    'cart.shipping.description': 'בחרו משלוח לפי מיקום, סוג מסירה ומשקל. המחיר מתעדכן לפי המטבע שנבחר.',
    'cart.shipping.hfd.title': 'בדיקת מחיר מול חברת HFD',
    'cart.shipping.hfd.description': 'הזינו כתובת מלאה, משקל והערך של ההזמנה כדי לקבל הצעת מחיר עדכנית דרך השרת.',
    'cart.shipping.hfd.city': 'עיר',
    'cart.shipping.hfd.cityPlaceholder': 'לדוגמה: תל אביב',
    'cart.shipping.hfd.street': 'רחוב',
    'cart.shipping.hfd.streetPlaceholder': 'לדוגמה: דיזנגוף',
    'cart.shipping.hfd.house': 'מספר בית',
    'cart.shipping.hfd.housePlaceholder': 'לדוגמה: 12א׳',
    'cart.shipping.hfd.contact': 'שם איש קשר',
    'cart.shipping.hfd.contactPlaceholder': 'שם מקבל המשלוח',
    'cart.shipping.hfd.phone': 'טלפון למשלוח',
    'cart.shipping.hfd.phonePlaceholder': '050-0000000',
    'cart.shipping.hfd.weight': 'משקל להזמנה (גרם)',
    'cart.shipping.hfd.weightPlaceholder': 'לדוגמה: 1200',
    'cart.shipping.hfd.weightHelper': 'מומלץ להשתמש במשקל שמחושב מתוך העגלה, או לעדכן ידנית.',
    'cart.shipping.hfd.value': 'שווי ההזמנה (₪)',
    'cart.shipping.hfd.valuePlaceholder': 'לדוגמה: 320',
    'cart.shipping.hfd.valueHelper': 'הערך כולל מע״מ אם רלוונטי, ומשמש לחישוב ביטוח.',
    'cart.shipping.hfd.cta': 'בדיקת מחיר ב-HFD',
    'cart.shipping.hfd.helper': 'בקשת המחיר נשלחת דרך השרת עם הטוקן של HFD (אם הוגדר).',
    'cart.shipping.hfd.estimate': 'הצעת מחיר משוערת (₪)',
    'cart.shipping.hfd.noEstimate': 'אין הערכת מחיר זמינה',
    'cart.shipping.hfd.weightLabel': 'משקל שנשלח',
    'cart.shipping.hfd.shipmentNumber': 'מספר משלוח שנוצר',
    'cart.shipping.hfd.apiError': 'שגיאה מ-HFD',
    'cart.shipping.hfd.addressError': 'נא למלא עיר ורחוב לפני בדיקת המחיר.',
    'cart.shipping.hfd.weightError': 'נא להזין משקל חוקי בגרמים לפני בדיקת המחיר.',
    'cart.shipping.hfd.errorGeneric': 'לא הצלחנו למשוך מחיר מ-HFD כרגע.',
    'cart.shipping.country': 'מדינת יעד למשלוח',
    'cart.shipping.country.placeholder': 'בחרו מדינה למשלוח',
    'cart.shipping.country.loading': 'טוען רשימת מדינות...',
    'cart.shipping.country.error': 'לא הצלחנו לטעון את רשימת המדינות. נסו שוב.',
    'cart.shipping.country.retry': 'רענון',
    'cart.shipping.country.empty': 'לא נמצאו מדינות זמינות למשלוח.',
    'cart.shipping.country.summary': 'מדינת יעד',
    'cart.shipping.country.unknown': 'מדינה לא נבחרה',
    'cart.shipping.carrier': 'חברת משלוחים',
    'cart.shipping.carrier.placeholder': 'בחרו את חברת המשלוחים המועדפת',
    'cart.shipping.carrier.loading': 'טוען חברות משלוחים...',
    'cart.shipping.carrier.error': 'לא הצלחנו לטעון חברות משלוחים.',
    'cart.shipping.carrier.retry': 'נסה שוב',
    'cart.shipping.carrier.empty': 'אין חברות משלוחים זמינות כעת.',
    'cart.shipping.carrier.summary': 'חברת משלוחים',
    'cart.shipping.carrier.unknown': 'לא נבחרה חברת משלוחים',
    'cart.shipping.carrier.contact': 'איש קשר',
    'cart.shipping.carrier.phone': 'טלפון',
    'cart.shipping.carrier.email': 'אימייל',
    'cart.shipping.carrier.notes': 'הערות',
    'cart.shipping.weight': 'טווח משקל',
    'cart.shipping.eta': 'זמן אספקה משוער',
    'cart.weight.kg': 'ק"ג',
    'cart.weight.perUnit': 'משקל ליחידה',
    'cart.weight.totalItem': 'משקל לכמות הנבחרת',
    'cart.weight.totalCart': 'משקל כולל להזמנה',
    'cart.weight.unknown': 'לא צויין משקל',
    'cart.weight.missingSummary': 'משקל לא זמין לפריטים אלה',
    'cart.payment.title': 'אמצעי תשלום',
    'cart.payment.card': 'כרטיס אשראי (J5 - הרשאה בלבד בעת ההזמנה)',
    'cart.payment.card.note': 'ביצוע חיוב בפועל יתבצע רק לאחר אישור המשלוח והיערכות המלאי.',
    'cart.order.note': 'אנחנו מבצעים הרשאת J5 בלבד ולא מחייבים כרטיסים עד לאישור משלוח.',
    'cart.payment.cash': 'מזומן באיסוף עצמי',
    'cart.payment.cash.note': 'תשלום מתבצע בעת האיסוף מהסניף, ללא חיוב מוקדם.',
    'cart.summary': 'סיכום הזמנה',
    'cart.items.total': 'סכום פריטים',
    'cart.shipping.cost': 'עלות משלוח',
    'cart.total': 'סה"כ להזמנה',
    'cart.checkout': 'שליחת הזמנה',
    'cart.checkout.secure': 'תשלום מאובטח באמצעות חברת האשראי',
    'cart.checkout.tip': 'מסיימים הזמנה במהירות',
    'cart.checkout.cardCta': 'מעבר לתשלום בכרטיס אשראי',
    'cart.checkout.cardCtaDescription': 'מעבירים אותך לדף סליקה מאובטח עם הרשאת J5 בלבד.',
    'cart.checkout.cardHelper': 'אין חיוב עד לאישור המשלוח, תוכלו גם לחזור לעגלה בכל שלב.',
    'cart.checkout.redirecting': 'מעביר לעמוד חיוב מאובטח...',
    'cart.checkout.paymentError': 'לא הצלחנו לפתוח את דף החיוב. נסו שוב או בחרו אמצעי תשלום אחר.',
    'cart.checkout.confirmation': 'שמירת פרטי ההזמנה בוצעה. ניצור קשר לאישור וחיוב רק לאחר אישור משלוח.',
    'cart.checkout.customerRequired': 'נא למלא שם ואימייל תקינים לפני מעבר לתשלום.',
    'cart.checkout.status.success': 'התשלום התקבל בהצלחה. נעדכן לגבי משלוח וחיוב.',
    'cart.checkout.status.cancel': 'התשלום בוטל. תוכלו לנסות שוב או לבחור אמצעי אחר.',
    'cart.checkout.status.error': 'אירעה שגיאה בעיבוד התשלום. אנא נסו שוב.',
    'payment.title': 'תשלום מאובטח באתר',
    'payment.subtitle': 'דף הסליקה מוטמע בתוך העיצוב המוכר של דף אחד.',
    'payment.helper': 'העמוד מאובטח והסליקה מתבצעת דרך הספק החיצוני מבלי לעזוב את האתר.',
    'payment.loading': 'טוען את דף הסליקה המאובטח...',
    'payment.missing': 'לא נמצאה כתובת לסליקה כעת.',
    'payment.missingHelper': 'חזרו לעגלה ונסו לפתוח מחדש את התשלום.',
    'payment.backToCart': 'חזרה לעגלה',
    'payment.orderLabel': 'מספר הזמנה:',
    'cart.customer.title': 'פרטי לקוח או אורח',
    'cart.customer.description': 'לצורך סליקה מאובטחת',
    'cart.customer.subtitle': 'היכנסו לחשבון או מלאו פרטי קשר למשלוח ואישור הזמנה.',
    'cart.customer.loginPrompt': 'כבר יש לכם חשבון?',
    'cart.customer.loginButton': 'התחברות לחשבון',
    'cart.customer.orGuest': 'או מלאו את פרטי המשלוח כהזמנת אורח',
    'cart.customer.name': 'שם מלא',
    'cart.customer.namePlaceholder': 'לדוגמה: ישראל ישראלי',
    'cart.customer.phone': 'טלפון',
    'cart.customer.phonePlaceholder': 'לדוגמה: 050-1234567',
    'cart.customer.email': 'אימייל לקבלת אישור הזמנה',
    'cart.customer.emailPlaceholder': 'name@email.com',
    'cart.customer.address': 'כתובת מלאה למשלוח',
    'cart.customer.addressPlaceholder': 'רחוב, מספר בית, עיר, מיקוד והערות למסירה',
    'cart.customer.address.detailsLabel': 'כתובת למשלוח',
    'cart.customer.address.specialInstructionsLabel': 'הערות למשלוח',
    'cart.customer.address.specialInstructionsPlaceholder': 'הנחיות למסירה, קוד כניסה או פרטים נוספים',
    'cart.customer.address.callIdLabel': 'מספר שיחה/סשן',
    'cart.customer.address.callIdPlaceholder': 'זיהוי שיחה או סשן למשלוח',
    'cart.customer.address.selectExisting': 'בחרו כתובת שמורה',
    'cart.customer.address.loadExisting': 'במידה ויש לכם כתובות שמורות נטען אותן כדי שתוכלו לתקן או לעדכן.',
    'cart.customer.address.additional': 'הוסף כתובת נוספת',
    'cart.customer.address.loading': 'טוען כתובות משלוח...',
    'cart.customer.address.none': 'לא נמצאו כתובות שמורות, מלאו כתובת חדשה.',
    'cart.customer.address.label': 'כתובת למשלוח',
    'cart.customer.address.default': 'ברירת מחדל',
    'cart.customer.address.inUse': 'בשימוש להזמנה',
    'cart.customer.address.streetLabel': 'רחוב',
    'cart.customer.address.streetPlaceholder': 'לדוגמה: יפו',
    'cart.customer.address.houseNumberLabel': 'מספר',
    'cart.customer.address.houseNumberPlaceholder': 'מספר בית',
    'cart.customer.address.cityLabel': 'עיר',
    'cart.customer.address.cityPlaceholder': 'לדוגמה: ירושלים',
    'cart.customer.address.stateLabel': 'מדינה/אזור',
    'cart.customer.address.statePlaceholder': 'לדוגמה: מחוז או מדינה',
    'cart.customer.address.zipLabel': 'מיקוד',
    'cart.customer.address.zipPlaceholder': 'לדוגמה: 91000',
    'cart.customer.address.countryLabel': 'ארץ',
    'cart.customer.address.countryPlaceholder': 'לדוגמה: ישראל',
    'cart.customer.address.entranceLabel': 'כניסה',
    'cart.customer.address.entrancePlaceholder': 'לדוגמה: ב',
    'cart.customer.address.apartmentLabel': 'דירה',
    'cart.customer.address.apartmentPlaceholder': 'לדוגמה: 8',
    'cart.customer.address.optional': 'אופציונלי',
    'cart.customer.address.markDefault': 'סמן ככתובת ברירת מחדל',
    'cart.customer.address.helper': 'בעת שיש כבר פרטים נטען אותם אוטומטית כדי שתוכלו לתקן או לעדכן לפני המשלוח.',
    'cart.customer.addresses.error': 'לא הצלחנו לטעון כתובות משלוח.',
    'cart.customer.helper': 'לפני מעבר לתשלום נבקש פרטים מלאים או התחברות כדי שנוכל לאשר את ההזמנה והמשלוח.',
    'cart.customer.required': 'נא להשלים שם, טלפון, אימייל ופרטי משלוח (רחוב, מספר ועיר) לפני מעבר לעמוד חיוב.',
    'cart.customer.pending': 'נדרש מילוי',
    'cart.customer.note': 'הפרטים עוברים לספק התשלום ונדרשים ליצירת דף חיוב מותאם.',
    'cart.steps.previous': 'חזרה לשלב הקודם',
    'cart.steps.next': 'המשך לשלב הבא',
    'cart.steps.completeSteps': 'סיימו את השלבים בעגלה ואז שלחו את ההזמנה מסיכום ההזמנה.',
    'account.title': 'חשבון לקוח',
    'account.subtitle': 'איזור אישי לניהול הזמנות, כתובות והעדפות קנייה.',
    'account.backToStore': 'חזרה לחנות',
    'account.logout': 'יציאה',
    'account.membership': 'חברות ומעמד',
    'account.storeCredit': 'קרדיט זמין',
    'account.creditDescription': 'ניתן למימוש בהזמנות אונליין או באיסוף עצמי.',
    'account.creditHistoryTitle': 'פעילות קרדיט',
    'account.creditHistoryDescription': 'רשימת הטעינות והקיזוזים כפי שנרשמו במערכת.',
    'account.creditLastUpdated': 'עודכן לאחרונה:',
    'account.creditCode': 'קוד',
    'account.creditDescriptionLabel': 'תיאור',
    'account.creditOrderId': 'מספר הזמנה/שימוש',
    'account.creditAmount': 'סכום',
    'account.creditRunningBalance': 'יתרה מצטברת',
    'account.creditLoading': 'טוען קרדיט לקוח...',
    'account.creditLoadError': 'אירעה שגיאה בטעינת הקרדיט. נסו שוב בעוד רגע.',
    'account.noCreditEntries': 'לא נמצאו תנועות קרדיט ללקוח זה.',
    'account.refresh': 'רענון נתונים',
    'tracking.title': 'מעקב אחרי משלוח',
    'tracking.subtitle': 'בדיקת סטטוס משלוח לפי מספר מעקב או הזמנה.',
    'tracking.numberLabel': 'מספר מעקב',
    'tracking.placeholder': 'לדוגמה: 123456 או מספר משלוח HFD',
    'tracking.courierLabel': 'חברת שילוח',
    'tracking.submit': 'בדיקת מעקב',
    'tracking.loading': 'טוען פרטי מעקב...',
    'tracking.statusHeader': 'פרטי משלוח',
    'tracking.latestUpdate': 'עדכון אחרון',
    'tracking.noStatuses': 'אין עדכוני סטטוס זמינים עדיין.',
    'tracking.errorGeneric': 'לא הצלחנו למשוך את סטטוס המשלוח כרגע.',
    'tracking.carrierUnsupported': 'בדיקת המעקב זמינה כרגע רק עבור HFD.',
    'tracking.delivered': 'נמסר',
    'tracking.inTransit': 'בדרך',
    'tracking.referenceLabel': 'אסמכתא',
    'tracking.codeLabel': 'קוד סטטוס',
    'account.security': 'אבטחה',
    'account.securityStatus': 'פרופיל מאומת',
    'account.securityDescription': 'התחברות מאובטחת עם אימות דו-שלבי והגנת תשלומים.',
    'account.orders': 'הזמנות',
    'account.recentOrders': 'הזמנות אחרונות',
    'account.ordersDescription': 'מציג משלוחים מועדפים, חבילות ממתינות וכל היסטוריית הקניות.',
    'account.ordersCount': 'הזמנות',
    'account.viewDetails': 'צפייה בפרטים',
    'account.orderId': 'מספר הזמנה',
    'account.date': 'תאריך',
    'account.status': 'סטטוס',
    'account.total': 'סה"כ',
    'account.courier': 'חברת שילוח',
    'account.trackingNumber': 'מספר מעקב',
    'account.addresses': 'כתובות משלוח',
    'account.manageAddresses': 'ניהול כתובות',
    'account.primary': 'ראשית',
    'account.addressesLoading': 'טוען כתובות משלוח...',
    'account.addressesEmpty': 'לא נמצאו כתובות שמורות. הוסיפו כתובת חדשה כדי להתחיל.',
    'account.addressesSaved': 'הכתובת נשמרה בהצלחה בטבלת הכתובות.',
    'account.addressesSaveError': 'לא הצלחנו לשמור את הכתובת. נסו שוב.',
    'account.addressForm.title': 'עדכון כתובות למשלוח',
    'account.addressForm.description': 'בחרו כתובת שמורה לעדכון או הוסיפו כתובת חדשה שתשמר בטבלה.',
    'account.addressForm.selectLabel': 'בחירת כתובת',
    'account.addressForm.newAddress': 'כתובת חדשה',
    'account.addressForm.street': 'רחוב',
    'account.addressForm.houseNumber': 'מספר בית',
    'account.addressForm.entrance': 'כניסה',
    'account.addressForm.apartment': 'דירה',
    'account.addressForm.city': 'עיר',
    'account.addressForm.state': 'מחוז / מדינה',
    'account.addressForm.zip': 'מיקוד',
    'account.addressForm.country': 'מדינה',
    'account.addressForm.phone': 'טלפון למשלוח',
    'account.addressForm.instructions': 'הערות לשליח',
    'account.addressForm.default': 'סימון כברירת מחדל',
    'account.addressForm.save': 'שמירת כתובת',
    'account.addressForm.saving': 'שומר כתובת...',
    'account.addressForm.requiredHint': 'שדות רחוב ועיר הם שדות חובה.',
    'account.addAddress': 'הוספת כתובת חדשה',
    'account.preferences': 'העדפות',
    'account.shoppingPreferences': 'העדפות קנייה פעילות',
    'account.language': 'שפת תצוגה',
    'account.currency': 'מטבע לחיוב',
    'account.notifications': 'התראות',
    'account.notificationsDescription': 'סטטוס הזמנה, אישורי תשלום ותזכורות מלאי חוזר.',
    'account.active': 'פעיל',
    'account.enabled': 'מופעל',
    'account.tabs.overview': 'סקירה כללית',
    'account.tabs.orders': 'הזמנות',
    'account.tabs.addresses': 'כתובות',
    'account.tabs.preferences': 'העדפות',
    'account.tabs.support': 'תמיכה',
    'account.summaryTitle': 'מעקב מהיר',
    'account.summaryDescription': 'תמונה נקייה של המשלוחים האחרונים והפעילות שלך.',
    'account.nextDelivery': 'המשלוח הבא',
    'account.awaitingPickup': 'ממתין לאיסוף',
    'account.quickActions': 'פעולות מהירות',
    'account.paymentMethods': 'אמצעי תשלום',
    'account.defaultPayment': 'כרטיס ברירת מחדל',
    'account.updatePayment': 'ניהול אמצעי תשלום',
    'account.support': 'תמיכה',
    'account.supportTitle': 'שירות לקוחות ישיר',
    'account.supportDescription': 'צוות החנות זמין לעדכון משלוחים, חשבוניות וייעוץ על ספרים.',
    'account.trackOrder': 'מעקב אחרי משלוח',
    'account.trackOrders': 'בדיקת משלוח',
    'account.trackOrdersTitle': 'מעקב משלוחים',
    'account.trackOrdersDescription': 'הזינו מספר מעקב ובחרו את חברת השילוח כדי לקבל מצב משלוח מעודכן.',
    'account.israelPost': 'דואר ישראל',
    'account.trackingPlaceholder': 'לדוגמה: IL123456789',
    'account.selectCourier': 'בחרו חברת שילוח',
    'account.trackNow': 'בדקו סטטוס',
    'account.contactSupport': 'צור קשר עם תמיכה',
    'account.customerId': 'מספר לקוח',
    'account.email': 'אימייל',
    'account.phone': 'טלפון',
    'account.location': 'מיקום',
    'account.customerTypeLabel': 'סוג לקוח',
    'account.languagePreference': 'שפת תקשורת',
    'account.profile.title': 'פרטי שם ושפה',
    'account.profile.description': 'עדכון שם פרטי/משפחה ושפת ברירת מחדל כפי שמופיעים בטבלת custe.',
    'account.profile.firstName': 'שם פרטי',
    'account.profile.lastName': 'שם משפחה',
    'account.profile.email': 'אימייל',
    'account.profile.phone': 'טלפון',
    'account.profile.fax': 'מספר פקס',
    'account.profile.language': 'שפת ברירת מחדל',
    'account.profile.languagePlaceholder': 'בחרו שפת ברירת מחדל',
    'account.profile.languageHebrew': 'עברית',
    'account.profile.languageEnglish': 'אנגלית',
    'account.profile.save': 'שמירת פרטי חשבון',
    'account.profile.saving': 'שומר פרטים...',
    'account.profile.success': 'פרטי החשבון נשמרו בטבלת custe.',
    'account.profile.error': 'לא הצלחנו לשמור את הפרטים. נסו שוב.',
    'account.profile.nameRequired': 'יש למלא שם פרטי ושם משפחה.',
    'login.title': 'התחברות לקוחות',
    'login.subtitle': 'היכנסו לצפייה בהזמנות, כתובות והעדפות אישיות.',
    'login.email': 'דוא"ל',
    'login.password': 'סיסמה',
    'login.remember': 'זכור אותי',
    'login.passwordMethod': 'כניסה עם סיסמה',
    'login.emailMethod': 'כניסה עם קוד למייל',
    'login.emailCode': 'קוד אימות מהמייל',
    'login.emailCodePlaceholder': '6 ספרות',
    'login.emailCodeRequest': 'שליחת קוד למייל',
    'login.emailCodeRequestWorking': 'שולח קוד...',
    'login.emailCodeSent': 'שלחנו קוד כניסה למייל שלכם',
    'login.forgot': 'שכחתם סיסמה?',
    'login.submit': 'כניסה לחשבון',
    'login.alt': 'או המשיכו כאורחים',
    'login.accountRequestTitle': 'יצירת או שחזור חשבון במייל',
    'login.accountRequestDescription': 'שלחו כתובת מייל ונחזיר הוראות ליצירת חשבון חדש או שחזור גישה קיימת.',
    'login.accountRequestPlaceholder': 'example@email.com',
    'login.accountRequestSubmit': 'שליחת בקשה',
    'login.accountRequestWorking': 'שולח בקשה...',
    'login.accountRequestSuccess': 'שלחנו הודעה עם הוראות ליצירת או שחזור חשבון.',
    'login.accountRequestError': 'לא הצלחנו לשלוח את הבקשה. נסו שוב בעוד רגע.',
    'login.resetTitle': 'שחזור סיסמה במייל',
    'login.resetDescription': 'קבלו סיסמה זמנית למייל כדי להיכנס מיד ולהחליף לסיסמה קבועה.',
    'login.resetPlaceholder': 'מייל לקבלת סיסמה זמנית',
    'login.resetSubmit': 'שלחו סיסמה זמנית',
    'login.resetWorking': 'שולח סיסמה זמנית...',
    'login.resetSuccess': 'שלחנו סיסמה זמנית לכתובת שהזנתם.',
    'login.resetError': 'לא הצלחנו לשלוח סיסמה זמנית. נסו שוב בעוד רגע.',
    'login.security': 'התחברות מאובטחת עם קוד חד פעמי ואימות מכשיר.',
    'login.cta': 'המשך לקטלוג',
    'login.welcome': 'ברוכים השבים',
    'login.status.loading': 'מתחבר...',
    'login.status.success': 'ההתחברות הצליחה',
    'login.error.missingFields': 'נא למלא אימייל וסיסמה.',
    'login.error.invalidCredentials': 'אימייל או סיסמה שגויים.',
    'login.error.invalidCode': 'קוד אימות שגוי או שפג תוקפו.',
    'login.error.tooManyAttempts': 'ניסיונות רבים מדי. בקשו קוד חדש וננסה שוב.',
    'login.error.generic': 'לא ניתן להתחבר כרגע. נסו שוב בעוד רגע.',
    'admin.title': 'לוח ניהול',
    'admin.signIn': 'כניסת מנהלים',
    'admin.disclaimer': 'הגישה מוגנת בסיסמה ונועדה לניהול מלאי והזמנות.',
    'admin.passwordLabel': 'סיסמת מנהל',
    'admin.passwordPlaceholder': 'הקלד סיסמת גישה',
    'admin.passwordHint': 'הסיסמה ניתנת לשינוי דרך VITE_ADMIN_PASSWORD.',
    'admin.enterPanel': 'כניסה ללוח ניהול',
    'admin.dashboard': 'מרכז הניהול',
    'admin.subtitle': 'ניהול ספרים, מלאי והזמנות במקום אחד.',
    'admin.backToStore': 'חזרה לחנות',
    'admin.logout': 'יציאה',
    'admin.ordersPending': 'הזמנות ממתינות',
    'admin.ordersProcessing': 'הזמנות בטיפול',
    'admin.inStockBooks': 'ספרים זמינים',
    'admin.featuredBooks': 'מוצרים מודגשים',
    'admin.books': 'ניהול ספרים',
    'admin.booksDescription': 'עדכון מלאי, הדגשות ומחירים.',
    'admin.totalItems': 'סה"כ רשומות',
    'admin.loading': 'טוען נתונים...',
    'admin.yes': 'כן',
    'admin.no': 'לא',
    'admin.inStock': 'במלאי',
    'admin.outOfStock': 'חסר במלאי',
    'admin.featured': 'מוצר מומלץ',
    'admin.priceIls': 'מחיר ₪',
    'admin.priceUsd': 'מחיר $',
    'admin.markOutOfStock': 'סמן כחסר',
    'admin.markInStock': 'החזר למלאי',
    'admin.removeFeatured': 'בטל הדגשה',
    'admin.addFeatured': 'הוסף להמלצות',
    'admin.addBook': 'הוספת ספר',
    'admin.addBookDescription': 'צור ספר חדש עם מחירים בסיסיים והשלם פרטים מאוחר יותר.',
    'admin.titleHebrew': 'כותרת בעברית',
    'admin.titleEnglish': 'כותרת באנגלית',
    'admin.createBook': 'צור ספר חדש',
    'admin.environmentNotice': 'השינויים נשמרים מקומית להדגמה. חברו API כדי להתמיד נתונים.',
      'admin.orders': 'הזמנות',
      'admin.ordersDescription': 'עדכון סטטוס והצגת סיכומי חיוב.',
      'admin.databasePreviewTitle': 'מסד נתונים',
      'admin.databasePreviewHeading': 'צפייה וחקירה של טבלאות',
      'admin.databasePreviewDescription': 'עברו למסך ייעודי כדי להציג את מבנה מסד הנתונים, לבחור טבלאות להצגה ולשלוף נתונים לדוגמה.',
      'admin.databasePreviewCta': 'פתח דף מסד נתונים',
      'admin.customersPage.title': 'ניהול לקוחות',
      'admin.customersPage.subtitle': 'רשימת לקוחות עם פרטי קשר, סטטוס ומסלול VIP.',
      'admin.customersPage.previewDescription': 'פתחו דף ניהול ייעודי לעדכון פרטי קשר, תגיות, סטטוס וחיובים.',
      'admin.customersPage.open': 'פתח דף לקוחות',
      'admin.customersPage.notice': 'נדרש להיכנס ללוח ניהול לפני גישה לרשימת הלקוחות.',
      'admin.customersPage.back': 'חזרה ללוח הניהול',
      'admin.customersPage.listTitle': 'רשימת לקוחות',
      'admin.customersPage.listSubtitle': 'סינון לפי סטטוס, חיפוש חכם ועדכון פרטים בזמן אמת.',
      'admin.customersPage.searchPlaceholder': 'חיפוש לפי שם, אימייל, טלפון או עיר',
      'admin.customersPage.searchLabel': 'חיפוש לקוחות',
      'admin.customersPage.filters.all': 'כל הסטטוסים',
      'admin.customersPage.status.active': 'פעיל',
      'admin.customersPage.status.paused': 'מושהה',
      'admin.customersPage.status.prospect': 'ליד',
      'admin.customersPage.cardTitle': 'מספר לקוח',
      'admin.customersPage.ordersCount': 'מספר הזמנות',
      'admin.customersPage.lastOrder': 'הזמנה אחרונה',
      'admin.customersPage.balance': 'יתרה',
      'admin.customersPage.contact': 'שם פרטי',
      'admin.customersPage.lastName': 'שם משפחה',
      'admin.customersPage.phone': 'טלפון',
      'admin.customersPage.email': 'אימייל',
      'admin.customersPage.city': 'עיר',
      'admin.customersPage.language': 'שפה',
      'admin.customersPage.tags': 'תגיות',
      'admin.customersPage.statusLabel': 'סטטוס',
      'admin.customersPage.tier': 'סוג לקוח',
      'admin.customersPage.tier.standard': 'רגיל',
      'admin.customersPage.tier.vip': 'VIP',
      'admin.customersPage.tier.wholesale': 'סיטונאי',
      'admin.customersPage.notes': 'הערות',
      'admin.customersPage.saved': 'נשמר',
      'admin.customersPage.save': 'שמור שינויים',
      'admin.customersPage.empty': 'לא נמצאו לקוחות תואמים לחיפוש.',
      'admin.customersPage.total': 'סה\"כ לקוחות',
      'admin.customersPage.summary.active': 'לקוחות פעילים',
      'admin.customersPage.summary.vip': 'לקוחות VIP',
      'admin.customersPage.summary.prospects': 'לידים פתוחים',
      'admin.schemaTitle': 'מבנה בסיס הנתונים',
      'admin.schemaDescription': 'רשימת הטבלאות והעמודות במסד הנתונים המרוחק.',
      'admin.schemaTablesLabel': 'טבלאות',
      'admin.schemaColumnsLabel': 'עמודות',
      'admin.schemaColumn': 'עמודה',
    'admin.schemaType': 'סוג',
    'admin.schemaNullable': 'Null',
    'admin.schemaKey': 'מפתח',
    'admin.schemaDefault': 'ברירת מחדל',
    'admin.schemaExtra': 'נוסף',
    'admin.schemaNoColumns': 'אין עמודות להצגה',
    'admin.schemaEmpty': 'לא נמצאו טבלאות במסד הנתונים.',
    'admin.schemaRetry': 'רענון',
    'admin.schemaError': 'לא ניתן למשוך את מבנה בסיס הנתונים כרגע.',
      'admin.status.pending': 'ממתין',
      'admin.status.processing': 'בטיפול',
    'admin.status.shipped': 'נשלח',
    'admin.status.delivered': 'נמסר',
    'admin.orderDate': 'תאריך הזמנה',
    'admin.itemsCount': 'מספר פריטים',
    'admin.totalAmount': 'סכום לחיוב',
    'admin.updateStatus': 'עדכון סטטוס',
      'admin.newBookDefaultDescription': 'ספר חדש שהתווסף דרך לוח הניהול.',
      'database.title': 'כלי נתונים',
      'database.heading': 'מסך ניהול מסד נתונים',
      'database.subtitle': 'צפו בטבלאות, סננו לפי סוג והציגו נתונים לדוגמה.',
      'database.backToAdmin': 'חזרה ללוח ניהול',
      'database.schemaSummary': '{count} טבלאות',
      'database.rowLimit': 'שורות לתצוגה',
      'database.refresh': 'רענון',
      'database.searchPlaceholder': 'חיפוש לפי טבלה או עמודה...',
      'database.filterAll': 'כל הסוגים',
      'database.filterTables': 'טבלאות',
      'database.filterViews': 'תצוגות',
      'database.showSelectedOnly': 'הצג רק טבלאות מסומנות',
      'database.selectionTitle': 'סינון לפי טבלאות',
      'database.selectionDescription': 'סמנו כאן את הטבלאות שתרצו להציג ברשימה למטה.',
      'database.selectedCount': '{count} טבלאות נבחרו',
      'database.selectAll': 'בחר הכל',
      'database.clearSelection': 'נקה בחירה',
      'database.applySelectionFilter': 'הצג רק נבחרות',
      'database.resetSelectionFilter': 'הצג את כל הטבלאות',
      'database.selectionHint': 'ניתן לסמן או להסיר סימון גם מתוך הרשימה הראשית של הטבלאות.',
      'database.loading': 'טוען נתונים...',
      'database.schemaError': 'לא ניתן לטעון את מבנה בסיס הנתונים כרגע.',
      'database.empty': 'לא נמצאו טבלאות במאגר.',
      'database.columnsLabel': '{count} עמודות',
      'database.selectTable': 'בחרו תצוגה',
      'database.viewData': 'הצג נתונים',
      'database.column': 'עמודה',
      'database.type': 'סוג',
      'database.nullable': 'Null',
      'database.key': 'מפתח',
      'database.default': 'ברירת מחדל',
      'database.extra': 'נוסף',
      'database.previewTitle': 'תצוגת נתונים',
      'database.tableDataError': 'טעינת הנתונים נכשלה.',
      'database.noData': 'אין נתונים זמינים להצגה.',
      'about.tagline': 'כל ספרי ברסלב במקום אחד',
    'about.title': 'אודות דף אחד',
    'about.description': 'דף אחד מרכז עבורכם ספרי קודש, חוברות, ודיגיטל מקוריים מבית ברסלב עם משלוחים בארץ ובעולם.',
    'about.focus': 'תחום פעילות',
    'about.focus.description': 'אנו מציעים ספרי ברסלב, חוברות לימוד, ומוצרים דיגיטליים לכל הגילאים—מבוגרים, נשים וילדים.',
    'about.experience': 'שירות והשראה',
    'about.experience.description': 'חוויית רכישה נעימה ומוקפדת עם תמיכה בשפה העברית והאנגלית והתאמת שילוח לכל יעד.',
    'contact.tagline': 'נשמח לשמוע מכם',
    'contact.title': 'יצירת קשר',
    'contact.subtitle': 'לשאלות, הזמנות מיוחדות או תמיכה—הנה הפרטים שלנו.',
    'contact.address.label': 'כתובת החנות',
    'contact.address.value': 'ירושלים, ישראל',
    'contact.phone.label': 'טלפון',
    'contact.phone.value': '076-598-9131',
    'contact.email.label': 'דוא"ל',
    'contact.hours.label': 'שעות פעילות',
    'contact.hours.value': 'א-ו 9:00-18:00',
    'policies.tagline': 'שקיפות מלאה',
    'policies.title': 'מדיניות אספקה, ביטול ופרטיות',
    'policies.subtitle': 'המדיניות שלנו מבטיחה שירות הוגן, עמידה בחוק והגנת פרטיות מלאה.',
    'policies.delivery.title': 'מדיניות אספקה',
    'policies.delivery.description': 'אספקה עד 7 ימי עסקים בישראל ומשלוחים בינלאומיים בהתאם ליעד (בדרך כלל 7-14 ימי עסקים).',
    'policies.cancellation.title': 'מדיניות ביטול עסקה',
    'policies.cancellation.description': 'ניתן לבטל עסקה בכפוף להחזרת מוצר במצב חדש ועמידה בהוראות החוק. החזר כספי יתואם לאחר אימות.',
    'policies.consumerLaw.title': 'חוק הגנת הצרכן',
    'policies.consumerLaw.description': 'תנאי הביטול יהיו ע"פ חוק הגנת הצרכן, תשמ"א – 1981, והוראות כל דין מחייב.',
    'policies.privacy.title': 'התחייבות לפרטיות',
    'policies.privacy.description': 'פרטי הלקוח מאובטחים ולא יועברו לצד ג׳ שלא לצורך השימוש באתר או עמידה בדרישות החוק.',
    'terms.tagline': 'תקנון האתר',
    'terms.title': 'תנאי שימוש ורכישה',
    'terms.subtitle': 'ביצוע הזמנה מהווה הסכמה מלאה לתקנון, למדיניות הביטול ולהצהרת הפרטיות שלנו.',
    'terms.acceptance': 'אישור לפני עסקה',
    'terms.acceptance.description': 'לפני תשלום נבקש את אישורכם לתקנון באמצעות צ׳ק בוקס או אישור מפורש בדף התשלום.',
    'terms.usage': 'שימוש באתר',
    'terms.usage.description': 'השימוש מיועד לרכישת ספרי קודש ומוצרים נלווים בלבד ובהתאם להנחיות שנקבעו בדף זה.',
    'terms.policyLink': 'קישור לתקנון',
    'terms.policyLink.description': 'התקנון מפורט בדף זה וזמין בכל עמוד תחת קישורי הפוטר.',
    'cart.terms.checkbox': 'אני מאשר/ת את תקנון האתר',
    'cart.terms.required': 'נא לאשר את התקנון לפני ביצוע הזמנה.',
    'cart.terms.link': 'לקריאת התקנון לחצו כאן',
  },
  en: {
    'site.title': 'Daf Echad',
    'site.tagline': 'Authentic Breslov Holy Books & Products',
    'nav.home': 'Home',
    'nav.books': 'Books',
    'nav.children': "Children's Channel",
    'nav.women': "Women's Channel",
    'nav.login': 'Login',
    'nav.account': 'Account',
    'nav.tracking': 'Track',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.terms': 'Terms',
    'nav.admin': 'Admin',
    'search.placeholder': 'Search books, author, category...',
    'search.button': 'Search',
    'kav.title': '24/6 Automated Order Line',
    'kav.phone': '+972.76.598.91.31',
    'categories.all': 'All Books',
    'categories.likutey': 'Likutey Moharan',
    'categories.prayer': 'Prayer',
    'categories.stories': 'Stories',
    'categories.children': 'Children',
    'categories.women': 'Women',
    'featured': 'Featured Products',
    'new.arrivals': 'New Arrivals',
    'wishlist.title': 'Your saved items',
    'wishlist.subtitle': 'Keep track of books you love and return when you are ready to order.',
    'wishlist.empty': 'No items in your wishlist yet',
    'collections': 'Collections',
    'brands': 'Brands',
    'recently.viewed': 'Recently Viewed',
    'footer.sitemap': 'Site Map',
    'footer.about': 'About Us',
    'footer.contact': 'Contact Us',
    'footer.donations': 'Donations',
    'footer.policies': 'Supply & Privacy Policy',
    'footer.terms': 'Site Terms',
    'footer.giftcard': 'Gift Card',
    'footer.balance': 'Check Balance',
    'footer.rights': '© All Rights Reserved',
    'cart.title': 'Cart & Checkout',
    'cart.subtitle': 'Review your items, delivery, and payment before confirming.',
    'cart.empty': 'Your cart is currently empty.',
    'cart.continue': 'Back to catalog',
    'cart.delivery.worldwide': 'Worldwide delivery available',
    'cart.delivery.multi': 'Multiple delivery methods: courier, post, or pickup.',
    'cart.items': 'Cart items',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.shipping.worldwide': 'Worldwide shipping',
    'cart.shipping.title': 'Shipping options',
    'cart.shipping.description': 'Choose shipping by location, delivery method, and weight. Prices follow your selected currency.',
    'cart.shipping.hfd.title': 'HFD shipping price check',
    'cart.shipping.hfd.description': 'Enter destination details, shipment weight, and order value to request a live rate from the server.',
    'cart.shipping.hfd.city': 'City',
    'cart.shipping.hfd.cityPlaceholder': 'e.g. Tel Aviv',
    'cart.shipping.hfd.street': 'Street',
    'cart.shipping.hfd.streetPlaceholder': 'e.g. Dizengoff',
    'cart.shipping.hfd.house': 'House number',
    'cart.shipping.hfd.housePlaceholder': 'e.g. 12A',
    'cart.shipping.hfd.contact': 'Contact name',
    'cart.shipping.hfd.contactPlaceholder': 'Recipient name',
    'cart.shipping.hfd.phone': 'Delivery phone',
    'cart.shipping.hfd.phonePlaceholder': '050-0000000',
    'cart.shipping.hfd.weight': 'Shipment weight (grams)',
    'cart.shipping.hfd.weightPlaceholder': 'e.g. 1200',
    'cart.shipping.hfd.weightHelper': 'We prefill the cart weight when available; adjust if you have a confirmed weight.',
    'cart.shipping.hfd.value': 'Order value (₪)',
    'cart.shipping.hfd.valuePlaceholder': 'e.g. 320',
    'cart.shipping.hfd.valueHelper': 'Include VAT where relevant. Used for insurance and carrier validation.',
    'cart.shipping.hfd.cta': 'Check HFD rate',
    'cart.shipping.hfd.helper': 'The request is sent through our server with your configured HFD token.',
    'cart.shipping.hfd.estimate': 'Estimated price (₪)',
    'cart.shipping.hfd.noEstimate': 'No estimate available yet',
    'cart.shipping.hfd.weightLabel': 'Weight sent',
    'cart.shipping.hfd.shipmentNumber': 'Shipment number from HFD',
    'cart.shipping.hfd.apiError': 'HFD response',
    'cart.shipping.hfd.addressError': 'Please provide a city and street before checking the rate.',
    'cart.shipping.hfd.weightError': 'Please enter a valid weight in grams before checking the rate.',
    'cart.shipping.hfd.errorGeneric': 'We could not fetch a rate from HFD right now.',
    'cart.shipping.country': 'Destination country',
    'cart.shipping.country.placeholder': 'Select a country for delivery',
    'cart.shipping.country.loading': 'Loading available countries...',
    'cart.shipping.country.error': 'Could not load the country list. Please try again.',
    'cart.shipping.country.retry': 'Reload',
    'cart.shipping.country.empty': 'No delivery countries are currently available.',
    'cart.shipping.country.summary': 'Destination',
    'cart.shipping.country.unknown': 'No country selected',
    'cart.shipping.carrier': 'Delivery carrier',
    'cart.shipping.carrier.placeholder': 'Select your preferred carrier',
    'cart.shipping.carrier.loading': 'Loading carriers...',
    'cart.shipping.carrier.error': 'Could not load carriers.',
    'cart.shipping.carrier.retry': 'Try again',
    'cart.shipping.carrier.empty': 'No carriers are currently available.',
    'cart.shipping.carrier.summary': 'Carrier',
    'cart.shipping.carrier.unknown': 'No carrier selected',
    'cart.shipping.carrier.contact': 'Contact',
    'cart.shipping.carrier.phone': 'Phone',
    'cart.shipping.carrier.email': 'Email',
    'cart.shipping.carrier.notes': 'Notes',
    'cart.shipping.weight': 'Weight band',
    'cart.shipping.eta': 'Estimated delivery',
    'cart.weight.kg': 'kg',
    'cart.weight.perUnit': 'Weight per item',
    'cart.weight.totalItem': 'Weight for selected quantity',
    'cart.weight.totalCart': 'Total order weight',
    'cart.weight.unknown': 'Weight not provided',
    'cart.weight.missingSummary': 'Weight not available for these items',
    'cart.payment.title': 'Payment methods',
    'cart.payment.card': 'Credit card (J5 authorization only at checkout)',
    'cart.payment.card.note': 'We only authorize the card and capture after shipping is confirmed.',
    'cart.order.note': 'Cards are not charged on order; a J5 authorization holds the shipment total.',
    'cart.payment.cash': 'Cash on pickup',
    'cart.payment.cash.note': 'Pay cash when collecting from our pickup desk. No upfront charge.',
    'cart.summary': 'Order summary',
    'cart.items.total': 'Items subtotal',
    'cart.shipping.cost': 'Shipping',
    'cart.total': 'Total for order',
    'cart.checkout': 'Submit order',
    'cart.checkout.secure': 'Secure checkout powered by our card provider',
    'cart.checkout.tip': 'A smoother way to finish your order',
    'cart.checkout.cardCta': 'Continue to credit card payment',
    'cart.checkout.cardCtaDescription': 'We will open a secure web checkout with a J5 authorization only.',
    'cart.checkout.cardHelper': 'You will not be charged until shipping is confirmed. You can return to the cart anytime.',
    'cart.checkout.redirecting': 'Opening secure payment...',
    'cart.checkout.paymentError': 'We could not open the payment page. Please try again or choose another method.',
    'cart.checkout.confirmation': 'Order details saved. We will authorize or collect payment only after delivery is confirmed.',
    'cart.checkout.customerRequired': 'Please enter a valid name and email before continuing to payment.',
    'cart.checkout.status.success': 'Payment completed successfully. We will finalize shipping and capture the charge after confirmation.',
    'cart.checkout.status.cancel': 'Payment was canceled. You can try again or switch payment methods.',
    'cart.checkout.status.error': 'We could not process the payment. Please try again.',
    'payment.title': 'Secure payment on site',
    'payment.subtitle': 'The hosted checkout is embedded inside the Daf Echad layout.',
    'payment.helper': 'Complete your payment without leaving the site. The form is secured by our external provider.',
    'payment.loading': 'Loading the secure payment form...',
    'payment.missing': 'No payment link is available right now.',
    'payment.missingHelper': 'Return to the cart and try opening the payment again.',
    'payment.backToCart': 'Back to cart',
    'payment.orderLabel': 'Order ID:',
    'cart.customer.title': 'Customer or guest details',
    'cart.customer.description': 'For secure payment',
    'cart.customer.subtitle': 'Sign in or share delivery contact details so we can approve the order.',
    'cart.customer.loginPrompt': 'Have an account?',
    'cart.customer.loginButton': 'Sign in to your account',
    'cart.customer.orGuest': 'or continue as a guest with delivery details',
    'cart.customer.name': 'Full name',
    'cart.customer.namePlaceholder': 'e.g. Sarah Cohen',
    'cart.customer.phone': 'Phone number',
    'cart.customer.phonePlaceholder': 'e.g. +1 212-555-0199',
    'cart.customer.email': 'Email for order confirmation',
    'cart.customer.emailPlaceholder': 'name@email.com',
    'cart.customer.address': 'Full delivery address',
    'cart.customer.addressPlaceholder': 'Street, building, city, postal code, and delivery notes',
    'cart.customer.address.detailsLabel': 'Delivery address',
    'cart.customer.address.specialInstructionsLabel': 'Special delivery notes',
    'cart.customer.address.specialInstructionsPlaceholder': 'Access code, delivery notes, or anything the courier should know',
    'cart.customer.address.callIdLabel': 'Call/session ID',
    'cart.customer.address.callIdPlaceholder': 'Internal session or call reference',
    'cart.customer.address.selectExisting': 'Choose a saved address',
    'cart.customer.address.loadExisting': 'If we have saved addresses for you, we will load them so you can update or fix them.',
    'cart.customer.address.additional': 'Add another address',
    'cart.customer.address.loading': 'Loading shipping addresses...',
    'cart.customer.address.none': 'No saved addresses found. Please enter a new one.',
    'cart.customer.address.label': 'Shipping address',
    'cart.customer.address.default': 'Default',
    'cart.customer.address.inUse': 'In use for this order',
    'cart.customer.address.streetLabel': 'Street',
    'cart.customer.address.streetPlaceholder': 'e.g. Maple Ave',
    'cart.customer.address.houseNumberLabel': 'Number',
    'cart.customer.address.houseNumberPlaceholder': 'Building or house number',
    'cart.customer.address.cityLabel': 'City',
    'cart.customer.address.cityPlaceholder': 'e.g. Jerusalem',
    'cart.customer.address.stateLabel': 'State/Region',
    'cart.customer.address.statePlaceholder': 'e.g. District or state',
    'cart.customer.address.zipLabel': 'ZIP/Postal code',
    'cart.customer.address.zipPlaceholder': 'e.g. 10001',
    'cart.customer.address.countryLabel': 'Country',
    'cart.customer.address.countryPlaceholder': 'e.g. Israel',
    'cart.customer.address.entranceLabel': 'Entrance',
    'cart.customer.address.entrancePlaceholder': 'e.g. B',
    'cart.customer.address.apartmentLabel': 'Apartment',
    'cart.customer.address.apartmentPlaceholder': 'e.g. 8',
    'cart.customer.address.optional': 'Optional',
    'cart.customer.address.markDefault': 'Mark as default address',
    'cart.customer.address.helper': 'We automatically load any saved delivery details so you can quickly update or correct them.',
    'cart.customer.addresses.error': 'Unable to load shipping addresses.',
    'cart.customer.helper': 'Before payment we need either a login or complete delivery contact details.',
    'cart.customer.required': 'Please complete name, phone, email, and shipping address (street, number, and city) before billing.',
    'cart.customer.pending': 'Needed',
    'cart.customer.note': 'We send these details to the payment provider to prepare the hosted checkout page.',
    'cart.steps.previous': 'Back to previous step',
    'cart.steps.next': 'Continue to next step',
    'cart.steps.completeSteps': 'Work through each step, then send the order from the summary.',
    'account.title': 'Customer account',
    'account.subtitle': 'Your private area for orders, addresses, and preferences.',
    'account.backToStore': 'Back to store',
    'account.logout': 'Sign out',
    'account.membership': 'Membership',
    'account.storeCredit': 'Store credit',
    'account.creditDescription': 'Can be applied to online checkout or pickup orders.',
    'account.creditHistoryTitle': 'Store credit activity',
    'account.creditHistoryDescription': 'Full ledger of credit loads and adjustments recorded for your account.',
    'account.creditLastUpdated': 'Last updated:',
    'account.creditCode': 'Code',
    'account.creditDescriptionLabel': 'Description',
    'account.creditOrderId': 'Order/usage ID',
    'account.creditAmount': 'Amount',
    'account.creditRunningBalance': 'Running balance',
    'account.creditLoading': 'Loading store credit...',
    'account.creditLoadError': 'We could not load your credit right now. Please try again shortly.',
    'account.noCreditEntries': 'No credit transactions were found for this customer.',
    'account.refresh': 'Refresh data',
    'tracking.title': 'Shipment tracking',
    'tracking.subtitle': 'Check live shipment status by tracking or order number.',
    'tracking.numberLabel': 'Tracking number',
    'tracking.placeholder': 'e.g. 123456 or HFD shipment number',
    'tracking.courierLabel': 'Carrier',
    'tracking.submit': 'Track shipment',
    'tracking.loading': 'Loading tracking details...',
    'tracking.statusHeader': 'Shipment details',
    'tracking.latestUpdate': 'Latest update',
    'tracking.noStatuses': 'No status updates are available yet.',
    'tracking.errorGeneric': 'We could not retrieve the shipment status right now.',
    'tracking.carrierUnsupported': 'Tracking is currently available for HFD shipments only.',
    'tracking.delivered': 'Delivered',
    'tracking.inTransit': 'In transit',
    'tracking.referenceLabel': 'Reference',
    'tracking.codeLabel': 'Status code',
    'account.security': 'Security',
    'account.securityStatus': 'Verified profile',
    'account.securityDescription': 'Secure login with 2FA and protected payments.',
    'account.orders': 'Orders',
    'account.recentOrders': 'Recent orders',
    'account.ordersDescription': 'See priority shipments, awaiting pickups, and full history.',
    'account.ordersCount': 'orders',
    'account.viewDetails': 'View details',
    'account.orderId': 'Order ID',
    'account.date': 'Date',
    'account.status': 'Status',
    'account.total': 'Total',
    'account.courier': 'Courier',
    'account.trackingNumber': 'Tracking number',
    'account.addresses': 'Shipping addresses',
    'account.manageAddresses': 'Manage addresses',
    'account.primary': 'Primary',
    'account.addressesLoading': 'Loading shipping addresses...',
    'account.addressesEmpty': 'No saved addresses found. Add one to get started.',
    'account.addressesSaved': 'Address saved to the addresses table successfully.',
    'account.addressesSaveError': 'Unable to save the address. Please try again.',
    'account.addressForm.title': 'Update shipping addresses',
    'account.addressForm.description': 'Select an address to edit or add a new one. Changes update the addresses table.',
    'account.addressForm.selectLabel': 'Choose an address',
    'account.addressForm.newAddress': 'New address',
    'account.addressForm.street': 'Street',
    'account.addressForm.houseNumber': 'House number',
    'account.addressForm.entrance': 'Entrance',
    'account.addressForm.apartment': 'Apartment',
    'account.addressForm.city': 'City',
    'account.addressForm.state': 'State / province',
    'account.addressForm.zip': 'ZIP / postal code',
    'account.addressForm.country': 'Country',
    'account.addressForm.phone': 'Delivery phone',
    'account.addressForm.instructions': 'Courier notes',
    'account.addressForm.default': 'Mark as default',
    'account.addressForm.save': 'Save address',
    'account.addressForm.saving': 'Saving address...',
    'account.addressForm.requiredHint': 'Street and city are required fields.',
    'account.addAddress': 'Add new address',
    'account.preferences': 'Preferences',
    'account.shoppingPreferences': 'Active shopping preferences',
    'account.language': 'Display language',
    'account.currency': 'Billing currency',
    'account.notifications': 'Notifications',
    'account.notificationsDescription': 'Order status, payment confirmations, and restock alerts.',
    'account.active': 'Active',
    'account.enabled': 'Enabled',
    'account.tabs.overview': 'Overview',
    'account.tabs.orders': 'Orders',
    'account.tabs.addresses': 'Addresses',
    'account.tabs.preferences': 'Preferences',
    'account.tabs.support': 'Support',
    'account.summaryTitle': 'Clean snapshot',
    'account.summaryDescription': 'A clear view of your latest shipments and activity.',
    'account.nextDelivery': 'Next delivery',
    'account.awaitingPickup': 'Awaiting pickup',
    'account.quickActions': 'Quick actions',
    'account.paymentMethods': 'Payment methods',
    'account.defaultPayment': 'Default card',
    'account.updatePayment': 'Manage payment options',
    'account.support': 'Support',
    'account.supportTitle': 'Direct customer care',
    'account.supportDescription': 'Our team can adjust shipments, invoices, or suggest the right sefer.',
    'account.trackOrder': 'Track order',
    'account.trackOrders': 'Track shipments',
    'account.trackOrdersTitle': 'Order tracking',
    'account.trackOrdersDescription': 'Enter your tracking number and select the carrier to see live updates.',
    'account.israelPost': 'Israel Post',
    'account.trackingPlaceholder': 'e.g. IL123456789',
    'account.selectCourier': 'Select a carrier',
    'account.trackNow': 'Track now',
    'account.contactSupport': 'Contact support',
    'account.customerId': 'Customer ID',
    'account.email': 'Email',
    'account.phone': 'Phone',
    'account.location': 'Location',
    'account.customerTypeLabel': 'Customer type',
    'account.languagePreference': 'Communication language',
    'account.profile.title': 'Name details',
    'account.profile.description': 'Manage first/last name and default language stored in the custe table.',
    'account.profile.firstName': 'First name',
    'account.profile.lastName': 'Last name',
    'account.profile.email': 'Email',
    'account.profile.phone': 'Phone',
    'account.profile.fax': 'Fax number',
    'account.profile.language': 'Default language',
    'account.profile.languagePlaceholder': 'Choose a default language',
    'account.profile.languageHebrew': 'Hebrew',
    'account.profile.languageEnglish': 'English',
    'account.profile.save': 'Save account details',
    'account.profile.saving': 'Saving details...',
    'account.profile.success': 'Account details saved to the custe table.',
    'account.profile.error': 'We could not save your details. Please try again.',
    'account.profile.nameRequired': 'First and last name are required.',
    'login.title': 'Customer login',
    'login.subtitle': 'Sign in to view your orders, addresses, and preferences.',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.passwordMethod': 'Password login',
    'login.emailMethod': 'Email code login',
    'login.emailCode': 'Verification code from email',
    'login.emailCodePlaceholder': '6 digits',
    'login.emailCodeRequest': 'Send code to email',
    'login.emailCodeRequestWorking': 'Sending code...',
    'login.emailCodeSent': 'We sent a login code to your email',
    'login.forgot': 'Forgot password?',
    'login.submit': 'Sign in',
    'login.alt': 'Or continue as guest',
    'login.accountRequestTitle': 'Create or restore your account by email',
    'login.accountRequestDescription': 'Send your email address and we will reply with instructions to set up or recover access.',
    'login.accountRequestPlaceholder': 'you@example.com',
    'login.accountRequestSubmit': 'Send request',
    'login.accountRequestWorking': 'Sending...',
    'login.accountRequestSuccess': 'We sent a message with steps to create or recover your account.',
    'login.accountRequestError': 'We could not send the request. Please try again shortly.',
    'login.resetTitle': 'Reset your password by email',
    'login.resetDescription': 'Receive a temporary password by email so you can sign in and set a new one right away.',
    'login.resetPlaceholder': 'Email for a temporary password',
    'login.resetSubmit': 'Send temporary password',
    'login.resetWorking': 'Sending password...',
    'login.resetSuccess': 'If the account exists, we sent a temporary password.',
    'login.resetError': 'We could not send a temporary password right now. Please try again shortly.',
    'login.security': 'Secure sign-in with OTP and device verification.',
    'login.cta': 'Go to catalog',
    'login.welcome': 'Welcome back',
    'login.status.loading': 'Signing you in...',
    'login.status.success': 'Signed in successfully',
    'login.error.missingFields': 'Please enter both email and password.',
    'login.error.invalidCredentials': 'Incorrect email or password.',
    'login.error.invalidCode': 'The verification code is incorrect or expired.',
    'login.error.tooManyAttempts': 'Too many attempts. Please request a new code.',
    'login.error.generic': 'We could not sign you in right now. Please try again shortly.',
    'admin.title': 'Admin panel',
    'admin.signIn': 'Administrator sign-in',
    'admin.disclaimer': 'Access is password protected for managing inventory and orders.',
    'admin.passwordLabel': 'Admin password',
    'admin.passwordPlaceholder': 'Enter access password',
    'admin.passwordHint': 'Configure a custom password with VITE_ADMIN_PASSWORD.',
    'admin.enterPanel': 'Enter admin panel',
    'admin.dashboard': 'Operations dashboard',
    'admin.subtitle': 'Manage books, stock, and orders from one place.',
    'admin.backToStore': 'Back to store',
    'admin.logout': 'Log out',
    'admin.ordersPending': 'Pending orders',
    'admin.ordersProcessing': 'Orders in progress',
    'admin.inStockBooks': 'Books in stock',
    'admin.featuredBooks': 'Featured titles',
    'admin.books': 'Book management',
    'admin.booksDescription': 'Update availability, highlights, and pricing.',
    'admin.totalItems': 'Total records',
    'admin.loading': 'Loading data...',
    'admin.yes': 'Yes',
    'admin.no': 'No',
    'admin.inStock': 'In stock',
    'admin.outOfStock': 'Out of stock',
    'admin.featured': 'Featured',
    'admin.priceIls': 'Price ₪',
    'admin.priceUsd': 'Price $',
    'admin.markOutOfStock': 'Mark out of stock',
    'admin.markInStock': 'Return to stock',
    'admin.removeFeatured': 'Remove highlight',
    'admin.addFeatured': 'Mark as featured',
    'admin.addBook': 'Add a book',
    'admin.addBookDescription': 'Create a new book with starter pricing and fill details later.',
    'admin.titleHebrew': 'Title (Hebrew)',
    'admin.titleEnglish': 'Title (English)',
    'admin.createBook': 'Create book',
    'admin.environmentNotice': 'Changes are stored locally for demo purposes. Connect your API to persist.',
      'admin.orders': 'Orders',
      'admin.ordersDescription': 'Update statuses and review billing summaries.',
      'admin.databasePreviewTitle': 'Database',
      'admin.databasePreviewHeading': 'Inspect tables with ease',
      'admin.databasePreviewDescription': 'Jump into a dedicated page to review the schema, pick which tables to show, and load sample rows.',
      'admin.databasePreviewCta': 'Open database page',
      'admin.customersPage.title': 'Customer management',
      'admin.customersPage.subtitle': 'Customer list with contact, status, and VIP tiers.',
      'admin.customersPage.previewDescription': 'Open a dedicated admin page to edit contact info, tags, statuses, and balances.',
      'admin.customersPage.open': 'Open customers page',
      'admin.customersPage.notice': 'Sign in to the admin console before accessing the customer list.',
      'admin.customersPage.back': 'Back to admin panel',
      'admin.customersPage.listTitle': 'Customer list',
      'admin.customersPage.listSubtitle': 'Filter by status, search quickly, and edit details live.',
      'admin.customersPage.searchPlaceholder': 'Search by name, email, phone, or city',
      'admin.customersPage.searchLabel': 'Search customers',
      'admin.customersPage.filters.all': 'All statuses',
      'admin.customersPage.status.active': 'Active',
      'admin.customersPage.status.paused': 'Paused',
      'admin.customersPage.status.prospect': 'Prospect',
      'admin.customersPage.cardTitle': 'Customer ID',
      'admin.customersPage.ordersCount': 'Orders',
      'admin.customersPage.lastOrder': 'Last order',
      'admin.customersPage.balance': 'Balance',
      'admin.customersPage.contact': 'First name',
      'admin.customersPage.lastName': 'Last name',
      'admin.customersPage.phone': 'Phone',
      'admin.customersPage.email': 'Email',
      'admin.customersPage.city': 'City',
      'admin.customersPage.language': 'Language',
      'admin.customersPage.tags': 'Tags',
      'admin.customersPage.statusLabel': 'Status',
      'admin.customersPage.tier': 'Customer tier',
      'admin.customersPage.tier.standard': 'Standard',
      'admin.customersPage.tier.vip': 'VIP',
      'admin.customersPage.tier.wholesale': 'Wholesale',
      'admin.customersPage.notes': 'Notes',
      'admin.customersPage.saved': 'Saved',
      'admin.customersPage.save': 'Save changes',
      'admin.customersPage.empty': 'No customers match your search yet.',
      'admin.customersPage.total': 'Total customers',
      'admin.customersPage.summary.active': 'Active customers',
      'admin.customersPage.summary.vip': 'VIP customers',
      'admin.customersPage.summary.prospects': 'Open prospects',
      'admin.schemaTitle': 'Database schema',
      'admin.schemaDescription': 'View tables and columns from the remote database.',
      'admin.schemaTablesLabel': 'Tables',
      'admin.schemaColumnsLabel': 'columns',
      'admin.schemaColumn': 'Column',
    'admin.schemaType': 'Type',
    'admin.schemaNullable': 'Null',
    'admin.schemaKey': 'Key',
    'admin.schemaDefault': 'Default',
    'admin.schemaExtra': 'Extra',
    'admin.schemaNoColumns': 'No columns available',
    'admin.schemaEmpty': 'No tables were found in the database.',
    'admin.schemaRetry': 'Refresh',
    'admin.schemaError': 'Unable to load the database schema right now.',
    'admin.status.pending': 'Pending',
    'admin.status.processing': 'Processing',
    'admin.status.shipped': 'Shipped',
    'admin.status.delivered': 'Delivered',
    'admin.orderDate': 'Order date',
    'admin.itemsCount': 'Items',
      'admin.totalAmount': 'Charge amount',
      'admin.updateStatus': 'Update status',
      'admin.newBookDefaultDescription': 'New book added from the admin panel.',
      'database.title': 'Data tools',
      'database.heading': 'Database control room',
      'database.subtitle': 'View tables, filter by type, and pull example rows.',
      'database.backToAdmin': 'Back to admin panel',
      'database.schemaSummary': '{count} tables',
      'database.rowLimit': 'Rows to preview',
      'database.refresh': 'Refresh',
      'database.searchPlaceholder': 'Search by table or column...',
      'database.filterAll': 'All types',
      'database.filterTables': 'Tables',
      'database.filterViews': 'Views',
      'database.showSelectedOnly': 'Show only selected tables',
      'database.selectionTitle': 'Filter by tables',
      'database.selectionDescription': 'Tick which tables should appear in the list below.',
      'database.selectedCount': '{count} tables selected',
      'database.selectAll': 'Select all',
      'database.clearSelection': 'Clear selection',
      'database.applySelectionFilter': 'Show selected tables',
      'database.resetSelectionFilter': 'Show all tables',
      'database.selectionHint': 'You can also toggle tables directly from the main list.',
      'database.loading': 'Loading data...',
      'database.schemaError': 'Unable to load the database schema right now.',
      'database.empty': 'No tables found in the database.',
      'database.columnsLabel': '{count} columns',
      'database.selectTable': 'Select table',
      'database.viewData': 'View data',
      'database.column': 'Column',
      'database.type': 'Type',
      'database.nullable': 'Null',
      'database.key': 'Key',
      'database.default': 'Default',
      'database.extra': 'Extra',
      'database.previewTitle': 'Data preview',
      'database.tableDataError': 'Unable to load rows for this table.',
      'database.noData': 'No data available to display.',
      'about.tagline': 'All Breslov books in one home',
    'about.title': 'About Daf Echad',
    'about.description': 'Daf Echad curates authentic Breslov holy books, pamphlets, and digital products with shipping in Israel and worldwide.',
    'about.focus': 'What we offer',
    'about.focus.description': 'Print and digital Breslov titles for adults, women, and children—plus guided study aids and curated bundles.',
    'about.experience': 'Service that inspires',
    'about.experience.description': 'A thoughtful shopping journey with Hebrew and English support and shipping options that fit your destination.',
    'contact.tagline': 'We are here for you',
    'contact.title': 'Contact us',
    'contact.subtitle': 'Questions, custom orders, or support? Reach us anytime with the details below.',
    'contact.address.label': 'Store address',
    'contact.address.value': 'Jerusalem, Israel',
    'contact.phone.label': 'Phone',
    'contact.phone.value': '+972-76-598-9131',
    'contact.email.label': 'Email',
    'contact.hours.label': 'Hours',
    'contact.hours.value': 'Sun-Fri 09:00-18:00',
    'policies.tagline': 'Clear and fair',
    'policies.title': 'Delivery, cancellation, and privacy policy',
    'policies.subtitle': 'Our policies protect your purchase, respect the law, and safeguard your privacy.',
    'policies.delivery.title': 'Supply policy',
    'policies.delivery.description': 'Delivery within Israel is up to 7 business days; international shipping follows destination timelines (typically 7-14 business days).',
    'policies.cancellation.title': 'Cancellation policy',
    'policies.cancellation.description': 'Orders can be cancelled subject to returning items in new condition and complying with applicable law. Refunds are coordinated after verification.',
    'policies.consumerLaw.title': 'Consumer protection',
    'policies.consumerLaw.description': 'Cancellation terms follow the Israeli Consumer Protection Law, 5741-1981, and all binding regulations.',
    'policies.privacy.title': 'Privacy commitment',
    'policies.privacy.description': "Customer details are secured and won't be shared with third parties except for site operation or legal compliance.",
    'terms.tagline': 'Site terms',
    'terms.title': 'Terms of use and purchase',
    'terms.subtitle': 'Placing an order means you accept our terms, cancellation rules, and privacy notice.',
    'terms.acceptance': 'Confirm before checkout',
    'terms.acceptance.description': 'Before payment we ask for your approval of the terms via checkbox or explicit confirmation on the payment step.',
    'terms.usage': 'Using the site',
    'terms.usage.description': 'Use is intended for purchasing holy books and related items only, according to the guidelines listed here.',
    'terms.policyLink': 'Accessing the terms',
    'terms.policyLink.description': 'The terms are detailed on this page and linked from every footer for easy reference.',
    'cart.terms.checkbox': 'I confirm the site terms',
    'cart.terms.required': 'Please approve the terms before placing your order.',
    'cart.terms.link': 'Read the full terms here',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('he');
  const [currency, setCurrency] = useState<Currency>('ILS');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, setCurrency, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
