import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'he' | 'en';
type Currency = 'ILS' | 'USD';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  setCurrency: (curr: Currency) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  he: {
    'site.title': 'דף אחד',
    'site.tagline': 'כל ספרי ברסלב במקום אחד',
    'nav.home': 'בית',
    'nav.books': 'ספרים',
    'nav.children': 'ערוץ ילדים',
    'nav.women': 'ערוץ נשים',
    'nav.login': 'התחברות',
    'nav.account': 'חשבון',
    'nav.cart': 'עגלה',
    'nav.admin': 'ניהול',
    'nav.about': 'אודות',
    'nav.contact': 'צור קשר',
    'nav.terms': 'תקנון',
    'search.placeholder': 'חיפוש ספרים, מחבר, קטגוריה...',
    'search.button': 'חיפוש',
    'kav.title': 'קו הזמנות אוטומטי 24/6',
    'kav.phone': '076.598.91.31',
    'categories.all': 'כל הספרים',
    'categories.likutey': 'ליקוטי מוהר"ן',
    'categories.prayer': 'תפילה',
    'categories.stories': 'סיפורי מעשיות',
    'categories.children': 'ילדים',
    'categories.women': 'נשים',
    'featured': 'מוצרים מומלצים',
    'new.arrivals': 'הגיעו לאחרונה',
    'collections': 'אוספים',
    'brands': 'מותגים',
    'recently.viewed': 'נצפו לאחרונה',
    'footer.sitemap': 'מפת האתר',
    'footer.about': 'אודות',
    'footer.contact': 'צור קשר',
    'footer.donations': 'תרומות',
    'footer.policies': 'מדיניות אספקה ופרטיות',
    'footer.terms': 'תקנון האתר',
    'footer.giftcard': 'כרטיס מתנה',
    'footer.balance': 'בדיקת יתרה',
    'footer.rights': '© כל הזכויות שמורות',
    'cart.title': 'עגלה והזמנה',
    'cart.subtitle': 'בדיקת פריטים, שילוח ואמצעי תשלום לפני שליחת ההזמנה.',
    'cart.empty': 'העגלה שלך ריקה כרגע.',
    'cart.continue': 'חזרה לקטלוג',
    'cart.delivery.worldwide': 'משלוחים לכל העולם',
    'cart.delivery.multi': 'מספר אפשרויות אספקה: שליח, דואר, או איסוף עצמי.',
    'cart.items': 'פריטי עגלה',
    'cart.quantity': 'כמות',
    'cart.remove': 'הסר',
    'cart.shipping.worldwide': 'משלוח בינלאומי',
    'cart.shipping.title': 'אפשרויות משלוח',
    'cart.shipping.description': 'בחרו משלוח לפי מיקום, סוג מסירה ומשקל. המחיר מתעדכן לפי המטבע שנבחר.',
    'cart.shipping.weight': 'טווח משקל',
    'cart.shipping.eta': 'זמן אספקה משוער',
    'cart.weight.kg': 'ק"ג',
    'cart.weight.perUnit': 'משקל ליחידה',
    'cart.weight.totalItem': 'משקל לכמות הנבחרת',
    'cart.weight.totalCart': 'משקל כולל להזמנה',
    'cart.weight.unknown': 'לא צויין משקל',
    'cart.weight.missingSummary': 'משקל לא זמין לפריטים אלה',
    'cart.payment.title': 'אמצעי תשלום',
    'cart.payment.card': 'כרטיס אשראי (J5 - הרשאה בלבד בעת ההזמנה)',
    'cart.payment.card.note': 'ביצוע חיוב בפועל יתבצע רק לאחר אישור המשלוח והיערכות המלאי.',
    'cart.order.note': 'אנחנו מבצעים הרשאת J5 בלבד ולא מחייבים כרטיסים עד לאישור משלוח.',
    'cart.payment.cash': 'מזומן באיסוף עצמי',
    'cart.payment.cash.note': 'תשלום מתבצע בעת האיסוף מהסניף, ללא חיוב מוקדם.',
    'cart.summary': 'סיכום הזמנה',
    'cart.items.total': 'סכום פריטים',
    'cart.shipping.cost': 'עלות משלוח',
    'cart.total': 'סה"כ להזמנה',
    'cart.checkout': 'שליחת הזמנה',
    'cart.checkout.confirmation': 'שמירת פרטי ההזמנה בוצעה. ניצור קשר לאישור וחיוב רק לאחר אישור משלוח.',
    'account.title': 'חשבון לקוח',
    'account.subtitle': 'איזור אישי לניהול הזמנות, כתובות והעדפות קנייה.',
    'account.backToStore': 'חזרה לחנות',
    'account.logout': 'יציאה',
    'account.membership': 'חברות ומעמד',
    'account.storeCredit': 'קרדיט זמין',
    'account.creditDescription': 'ניתן למימוש בהזמנות אונליין או באיסוף עצמי.',
    'account.security': 'אבטחה',
    'account.securityStatus': 'פרופיל מאומת',
    'account.securityDescription': 'התחברות מאובטחת עם אימות דו-שלבי והגנת תשלומים.',
    'account.orders': 'הזמנות',
    'account.recentOrders': 'הזמנות אחרונות',
    'account.ordersDescription': 'מציג משלוחים מועדפים, חבילות ממתינות וכל היסטוריית הקניות.',
    'account.ordersCount': 'הזמנות',
    'account.viewDetails': 'צפייה בפרטים',
    'account.orderId': 'מספר הזמנה',
    'account.date': 'תאריך',
    'account.status': 'סטטוס',
    'account.total': 'סה"כ',
    'account.courier': 'חברת שילוח',
    'account.trackingNumber': 'מספר מעקב',
    'account.addresses': 'כתובות משלוח',
    'account.manageAddresses': 'ניהול כתובות',
    'account.primary': 'ראשית',
    'account.addAddress': 'הוספת כתובת חדשה',
    'account.preferences': 'העדפות',
    'account.shoppingPreferences': 'העדפות קנייה פעילות',
    'account.language': 'שפת תצוגה',
    'account.currency': 'מטבע לחיוב',
    'account.notifications': 'התראות',
    'account.notificationsDescription': 'סטטוס הזמנה, אישורי תשלום ותזכורות מלאי חוזר.',
    'account.active': 'פעיל',
    'account.enabled': 'מופעל',
    'account.tabs.overview': 'סקירה כללית',
    'account.tabs.orders': 'הזמנות',
    'account.tabs.addresses': 'כתובות',
    'account.tabs.preferences': 'העדפות',
    'account.tabs.support': 'תמיכה',
    'account.summaryTitle': 'מעקב מהיר',
    'account.summaryDescription': 'תמונה נקייה של המשלוחים האחרונים והפעילות שלך.',
    'account.nextDelivery': 'המשלוח הבא',
    'account.awaitingPickup': 'ממתין לאיסוף',
    'account.quickActions': 'פעולות מהירות',
    'account.paymentMethods': 'אמצעי תשלום',
    'account.defaultPayment': 'כרטיס ברירת מחדל',
    'account.updatePayment': 'ניהול אמצעי תשלום',
    'account.support': 'תמיכה',
    'account.supportTitle': 'שירות לקוחות ישיר',
    'account.supportDescription': 'צוות החנות זמין לעדכון משלוחים, חשבוניות וייעוץ על ספרים.',
    'account.trackOrder': 'מעקב אחרי משלוח',
    'account.trackOrders': 'בדיקת משלוח',
    'account.trackOrdersTitle': 'מעקב משלוחים',
    'account.trackOrdersDescription': 'הזינו מספר מעקב ובחרו את חברת השילוח כדי לקבל מצב משלוח מעודכן.',
    'account.trackingPlaceholder': 'לדוגמה: IL123456789',
    'account.selectCourier': 'בחרו חברת שילוח',
    'account.trackNow': 'בדקו סטטוס',
    'account.contactSupport': 'צור קשר עם תמיכה',
    'account.customerDetails': 'פרטי לקוח',
    'account.customerDetailsTitle': 'פרטי חשבון',
    'account.customerDetailsDescription': 'הנתונים המעודכנים כפי שהם מופיעים בטבלה.',
    'account.customerId': 'מספר לקוח',
    'account.email': 'אימייל',
    'account.phone': 'טלפון',
    'account.location': 'מיקום',
    'account.customerTypeLabel': 'סוג לקוח',
    'account.languagePreference': 'שפת תקשורת',
    'login.title': 'התחברות לקוחות',
    'login.subtitle': 'היכנסו לצפייה בהזמנות, כתובות והעדפות אישיות.',
    'login.email': 'דוא"ל',
    'login.password': 'סיסמה',
    'login.remember': 'זכור אותי',
    'login.forgot': 'שכחתם סיסמה?',
    'login.submit': 'כניסה לחשבון',
    'login.alt': 'או המשיכו כאורחים',
    'login.accountRequestTitle': 'יצירת או שחזור חשבון במייל',
    'login.accountRequestDescription': 'שלחו כתובת מייל ונחזיר הוראות ליצירת חשבון חדש או שחזור גישה קיימת.',
    'login.accountRequestPlaceholder': 'example@email.com',
    'login.accountRequestSubmit': 'שליחת בקשה',
    'login.accountRequestWorking': 'שולח בקשה...',
    'login.accountRequestSuccess': 'שלחנו הודעה עם הוראות ליצירת או שחזור חשבון.',
    'login.accountRequestError': 'לא הצלחנו לשלוח את הבקשה. נסו שוב בעוד רגע.',
    'login.security': 'התחברות מאובטחת עם קוד חד פעמי ואימות מכשיר.',
    'login.cta': 'המשך לקטלוג',
    'login.welcome': 'ברוכים השבים',
    'admin.title': 'לוח ניהול',
    'admin.signIn': 'כניסת מנהלים',
    'admin.disclaimer': 'הגישה מוגנת בסיסמה ונועדה לניהול מלאי והזמנות.',
    'admin.passwordLabel': 'סיסמת מנהל',
    'admin.passwordPlaceholder': 'הקלד סיסמת גישה',
    'admin.passwordHint': 'הסיסמה ניתנת לשינוי דרך VITE_ADMIN_PASSWORD.',
    'admin.enterPanel': 'כניסה ללוח ניהול',
    'admin.dashboard': 'מרכז הניהול',
    'admin.subtitle': 'ניהול ספרים, מלאי והזמנות במקום אחד.',
    'admin.backToStore': 'חזרה לחנות',
    'admin.logout': 'יציאה',
    'admin.ordersPending': 'הזמנות ממתינות',
    'admin.ordersProcessing': 'הזמנות בטיפול',
    'admin.inStockBooks': 'ספרים זמינים',
    'admin.featuredBooks': 'מוצרים מודגשים',
    'admin.books': 'ניהול ספרים',
    'admin.booksDescription': 'עדכון מלאי, הדגשות ומחירים.',
    'admin.totalItems': 'סה"כ רשומות',
    'admin.loading': 'טוען נתונים...',
    'admin.inStock': 'במלאי',
    'admin.outOfStock': 'חסר במלאי',
    'admin.featured': 'מוצר מומלץ',
    'admin.priceIls': 'מחיר ₪',
    'admin.priceUsd': 'מחיר $',
    'admin.markOutOfStock': 'סמן כחסר',
    'admin.markInStock': 'החזר למלאי',
    'admin.removeFeatured': 'בטל הדגשה',
    'admin.addFeatured': 'הוסף להמלצות',
    'admin.addBook': 'הוספת ספר',
    'admin.addBookDescription': 'צור ספר חדש עם מחירים בסיסיים והשלם פרטים מאוחר יותר.',
    'admin.titleHebrew': 'כותרת בעברית',
    'admin.titleEnglish': 'כותרת באנגלית',
    'admin.createBook': 'צור ספר חדש',
    'admin.environmentNotice': 'השינויים נשמרים מקומית להדגמה. חברו API כדי להתמיד נתונים.',
    'admin.orders': 'הזמנות',
    'admin.ordersDescription': 'עדכון סטטוס והצגת סיכומי חיוב.',
    'admin.status.pending': 'ממתין',
    'admin.status.processing': 'בטיפול',
    'admin.status.shipped': 'נשלח',
    'admin.status.delivered': 'נמסר',
    'admin.orderDate': 'תאריך הזמנה',
    'admin.itemsCount': 'מספר פריטים',
    'admin.totalAmount': 'סכום לחיוב',
    'admin.updateStatus': 'עדכון סטטוס',
    'admin.newBookDefaultDescription': 'ספר חדש שהתווסף דרך לוח הניהול.',
    'about.tagline': 'כל ספרי ברסלב במקום אחד',
    'about.title': 'אודות דף אחד',
    'about.description': 'דף אחד מרכז עבורכם ספרי קודש, חוברות, ודיגיטל מקוריים מבית ברסלב עם משלוחים בארץ ובעולם.',
    'about.focus': 'תחום פעילות',
    'about.focus.description': 'אנו מציעים ספרי ברסלב, חוברות לימוד, ומוצרים דיגיטליים לכל הגילאים—מבוגרים, נשים וילדים.',
    'about.experience': 'שירות והשראה',
    'about.experience.description': 'חוויית רכישה נעימה ומוקפדת עם תמיכה בשפה העברית והאנגלית והתאמת שילוח לכל יעד.',
    'contact.tagline': 'נשמח לשמוע מכם',
    'contact.title': 'יצירת קשר',
    'contact.subtitle': 'לשאלות, הזמנות מיוחדות או תמיכה—הנה הפרטים שלנו.',
    'contact.address.label': 'כתובת החנות',
    'contact.address.value': 'ירושלים, ישראל',
    'contact.phone.label': 'טלפון',
    'contact.phone.value': '076-598-9131',
    'contact.email.label': 'דוא"ל',
    'contact.hours.label': 'שעות פעילות',
    'contact.hours.value': 'א-ו 9:00-18:00',
    'policies.tagline': 'שקיפות מלאה',
    'policies.title': 'מדיניות אספקה, ביטול ופרטיות',
    'policies.subtitle': 'המדיניות שלנו מבטיחה שירות הוגן, עמידה בחוק והגנת פרטיות מלאה.',
    'policies.delivery.title': 'מדיניות אספקה',
    'policies.delivery.description': 'אספקה עד 7 ימי עסקים בישראל ומשלוחים בינלאומיים בהתאם ליעד (בדרך כלל 7-14 ימי עסקים).',
    'policies.cancellation.title': 'מדיניות ביטול עסקה',
    'policies.cancellation.description': 'ניתן לבטל עסקה בכפוף להחזרת מוצר במצב חדש ועמידה בהוראות החוק. החזר כספי יתואם לאחר אימות.',
    'policies.consumerLaw.title': 'חוק הגנת הצרכן',
    'policies.consumerLaw.description': 'תנאי הביטול יהיו ע"פ חוק הגנת הצרכן, תשמ"א – 1981, והוראות כל דין מחייב.',
    'policies.privacy.title': 'התחייבות לפרטיות',
    'policies.privacy.description': 'פרטי הלקוח מאובטחים ולא יועברו לצד ג׳ שלא לצורך השימוש באתר או עמידה בדרישות החוק.',
    'terms.tagline': 'תקנון האתר',
    'terms.title': 'תנאי שימוש ורכישה',
    'terms.subtitle': 'ביצוע הזמנה מהווה הסכמה מלאה לתקנון, למדיניות הביטול ולהצהרת הפרטיות שלנו.',
    'terms.acceptance': 'אישור לפני עסקה',
    'terms.acceptance.description': 'לפני תשלום נבקש את אישורכם לתקנון באמצעות צ׳ק בוקס או אישור מפורש בדף התשלום.',
    'terms.usage': 'שימוש באתר',
    'terms.usage.description': 'השימוש מיועד לרכישת ספרי קודש ומוצרים נלווים בלבד ובהתאם להנחיות שנקבעו בדף זה.',
    'terms.policyLink': 'קישור לתקנון',
    'terms.policyLink.description': 'התקנון מפורט בדף זה וזמין בכל עמוד תחת קישורי הפוטר.',
    'cart.terms.checkbox': 'אני מאשר/ת את תקנון האתר',
    'cart.terms.required': 'נא לאשר את התקנון לפני ביצוע הזמנה.',
    'cart.terms.link': 'לקריאת התקנון לחצו כאן',
  },
  en: {
    'site.title': 'Daf Echad',
    'site.tagline': 'Authentic Breslov Holy Books & Products',
    'nav.home': 'Home',
    'nav.books': 'Books',
    'nav.children': "Children's Channel",
    'nav.women': "Women's Channel",
    'nav.login': 'Login',
    'nav.account': 'Account',
    'nav.cart': 'Cart',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.terms': 'Terms',
    'nav.admin': 'Admin',
    'search.placeholder': 'Search books, author, category...',
    'search.button': 'Search',
    'kav.title': '24/6 Automated Order Line',
    'kav.phone': '+972.76.598.91.31',
    'categories.all': 'All Books',
    'categories.likutey': 'Likutey Moharan',
    'categories.prayer': 'Prayer',
    'categories.stories': 'Stories',
    'categories.children': 'Children',
    'categories.women': 'Women',
    'featured': 'Featured Products',
    'new.arrivals': 'New Arrivals',
    'collections': 'Collections',
    'brands': 'Brands',
    'recently.viewed': 'Recently Viewed',
    'footer.sitemap': 'Site Map',
    'footer.about': 'About Us',
    'footer.contact': 'Contact Us',
    'footer.donations': 'Donations',
    'footer.policies': 'Supply & Privacy Policy',
    'footer.terms': 'Site Terms',
    'footer.giftcard': 'Gift Card',
    'footer.balance': 'Check Balance',
    'footer.rights': '© All Rights Reserved',
    'cart.title': 'Cart & Checkout',
    'cart.subtitle': 'Review your items, delivery, and payment before confirming.',
    'cart.empty': 'Your cart is currently empty.',
    'cart.continue': 'Back to catalog',
    'cart.delivery.worldwide': 'Worldwide delivery available',
    'cart.delivery.multi': 'Multiple delivery methods: courier, post, or pickup.',
    'cart.items': 'Cart items',
    'cart.quantity': 'Quantity',
    'cart.remove': 'Remove',
    'cart.shipping.worldwide': 'Worldwide shipping',
    'cart.shipping.title': 'Shipping options',
    'cart.shipping.description': 'Choose shipping by location, delivery method, and weight. Prices follow your selected currency.',
    'cart.shipping.weight': 'Weight band',
    'cart.shipping.eta': 'Estimated delivery',
    'cart.weight.kg': 'kg',
    'cart.weight.perUnit': 'Weight per item',
    'cart.weight.totalItem': 'Weight for selected quantity',
    'cart.weight.totalCart': 'Total order weight',
    'cart.weight.unknown': 'Weight not provided',
    'cart.weight.missingSummary': 'Weight not available for these items',
    'cart.payment.title': 'Payment methods',
    'cart.payment.card': 'Credit card (J5 authorization only at checkout)',
    'cart.payment.card.note': 'We only authorize the card and capture after shipping is confirmed.',
    'cart.order.note': 'Cards are not charged on order; a J5 authorization holds the shipment total.',
    'cart.payment.cash': 'Cash on pickup',
    'cart.payment.cash.note': 'Pay cash when collecting from our pickup desk. No upfront charge.',
    'cart.summary': 'Order summary',
    'cart.items.total': 'Items subtotal',
    'cart.shipping.cost': 'Shipping',
    'cart.total': 'Total for order',
    'cart.checkout': 'Submit order',
    'cart.checkout.confirmation': 'Order details saved. We will authorize or collect payment only after delivery is confirmed.',
    'account.title': 'Customer account',
    'account.subtitle': 'Your private area for orders, addresses, and preferences.',
    'account.backToStore': 'Back to store',
    'account.logout': 'Sign out',
    'account.membership': 'Membership',
    'account.storeCredit': 'Store credit',
    'account.creditDescription': 'Can be applied to online checkout or pickup orders.',
    'account.security': 'Security',
    'account.securityStatus': 'Verified profile',
    'account.securityDescription': 'Secure login with 2FA and protected payments.',
    'account.orders': 'Orders',
    'account.recentOrders': 'Recent orders',
    'account.ordersDescription': 'See priority shipments, awaiting pickups, and full history.',
    'account.ordersCount': 'orders',
    'account.viewDetails': 'View details',
    'account.orderId': 'Order ID',
    'account.date': 'Date',
    'account.status': 'Status',
    'account.total': 'Total',
    'account.courier': 'Courier',
    'account.trackingNumber': 'Tracking number',
    'account.addresses': 'Shipping addresses',
    'account.manageAddresses': 'Manage addresses',
    'account.primary': 'Primary',
    'account.addAddress': 'Add new address',
    'account.preferences': 'Preferences',
    'account.shoppingPreferences': 'Active shopping preferences',
    'account.language': 'Display language',
    'account.currency': 'Billing currency',
    'account.notifications': 'Notifications',
    'account.notificationsDescription': 'Order status, payment confirmations, and restock alerts.',
    'account.active': 'Active',
    'account.enabled': 'Enabled',
    'account.tabs.overview': 'Overview',
    'account.tabs.orders': 'Orders',
    'account.tabs.addresses': 'Addresses',
    'account.tabs.preferences': 'Preferences',
    'account.tabs.support': 'Support',
    'account.summaryTitle': 'Clean snapshot',
    'account.summaryDescription': 'A clear view of your latest shipments and activity.',
    'account.nextDelivery': 'Next delivery',
    'account.awaitingPickup': 'Awaiting pickup',
    'account.quickActions': 'Quick actions',
    'account.paymentMethods': 'Payment methods',
    'account.defaultPayment': 'Default card',
    'account.updatePayment': 'Manage payment options',
    'account.support': 'Support',
    'account.supportTitle': 'Direct customer care',
    'account.supportDescription': 'Our team can adjust shipments, invoices, or suggest the right sefer.',
    'account.trackOrder': 'Track order',
    'account.trackOrders': 'Track shipments',
    'account.trackOrdersTitle': 'Order tracking',
    'account.trackOrdersDescription': 'Enter your tracking number and select the carrier to see live updates.',
    'account.trackingPlaceholder': 'e.g. IL123456789',
    'account.selectCourier': 'Select a carrier',
    'account.trackNow': 'Track now',
    'account.contactSupport': 'Contact support',
    'account.customerDetails': 'Customer details',
    'account.customerDetailsTitle': 'Account details',
    'account.customerDetailsDescription': 'Keep the account info matched exactly to the table view.',
    'account.customerId': 'Customer ID',
    'account.email': 'Email',
    'account.phone': 'Phone',
    'account.location': 'Location',
    'account.customerTypeLabel': 'Customer type',
    'account.languagePreference': 'Communication language',
    'login.title': 'Customer login',
    'login.subtitle': 'Sign in to view your orders, addresses, and preferences.',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.submit': 'Sign in',
    'login.alt': 'Or continue as guest',
    'login.accountRequestTitle': 'Create or restore your account by email',
    'login.accountRequestDescription': 'Send your email address and we will reply with instructions to set up or recover access.',
    'login.accountRequestPlaceholder': 'you@example.com',
    'login.accountRequestSubmit': 'Send request',
    'login.accountRequestWorking': 'Sending...',
    'login.accountRequestSuccess': 'We sent a message with steps to create or recover your account.',
    'login.accountRequestError': 'We could not send the request. Please try again shortly.',
    'login.security': 'Secure sign-in with OTP and device verification.',
    'login.cta': 'Go to catalog',
    'login.welcome': 'Welcome back',
    'admin.title': 'Admin panel',
    'admin.signIn': 'Administrator sign-in',
    'admin.disclaimer': 'Access is password protected for managing inventory and orders.',
    'admin.passwordLabel': 'Admin password',
    'admin.passwordPlaceholder': 'Enter access password',
    'admin.passwordHint': 'Configure a custom password with VITE_ADMIN_PASSWORD.',
    'admin.enterPanel': 'Enter admin panel',
    'admin.dashboard': 'Operations dashboard',
    'admin.subtitle': 'Manage books, stock, and orders from one place.',
    'admin.backToStore': 'Back to store',
    'admin.logout': 'Log out',
    'admin.ordersPending': 'Pending orders',
    'admin.ordersProcessing': 'Orders in progress',
    'admin.inStockBooks': 'Books in stock',
    'admin.featuredBooks': 'Featured titles',
    'admin.books': 'Book management',
    'admin.booksDescription': 'Update availability, highlights, and pricing.',
    'admin.totalItems': 'Total records',
    'admin.loading': 'Loading data...',
    'admin.inStock': 'In stock',
    'admin.outOfStock': 'Out of stock',
    'admin.featured': 'Featured',
    'admin.priceIls': 'Price ₪',
    'admin.priceUsd': 'Price $',
    'admin.markOutOfStock': 'Mark out of stock',
    'admin.markInStock': 'Return to stock',
    'admin.removeFeatured': 'Remove highlight',
    'admin.addFeatured': 'Mark as featured',
    'admin.addBook': 'Add a book',
    'admin.addBookDescription': 'Create a new book with starter pricing and fill details later.',
    'admin.titleHebrew': 'Title (Hebrew)',
    'admin.titleEnglish': 'Title (English)',
    'admin.createBook': 'Create book',
    'admin.environmentNotice': 'Changes are stored locally for demo purposes. Connect your API to persist.',
    'admin.orders': 'Orders',
    'admin.ordersDescription': 'Update statuses and review billing summaries.',
    'admin.status.pending': 'Pending',
    'admin.status.processing': 'Processing',
    'admin.status.shipped': 'Shipped',
    'admin.status.delivered': 'Delivered',
    'admin.orderDate': 'Order date',
    'admin.itemsCount': 'Items',
    'admin.totalAmount': 'Charge amount',
    'admin.updateStatus': 'Update status',
    'admin.newBookDefaultDescription': 'New book added from the admin panel.',
    'about.tagline': 'All Breslov books in one home',
    'about.title': 'About Daf Echad',
    'about.description': 'Daf Echad curates authentic Breslov holy books, pamphlets, and digital products with shipping in Israel and worldwide.',
    'about.focus': 'What we offer',
    'about.focus.description': 'Print and digital Breslov titles for adults, women, and children—plus guided study aids and curated bundles.',
    'about.experience': 'Service that inspires',
    'about.experience.description': 'A thoughtful shopping journey with Hebrew and English support and shipping options that fit your destination.',
    'contact.tagline': 'We are here for you',
    'contact.title': 'Contact us',
    'contact.subtitle': 'Questions, custom orders, or support? Reach us anytime with the details below.',
    'contact.address.label': 'Store address',
    'contact.address.value': 'Jerusalem, Israel',
    'contact.phone.label': 'Phone',
    'contact.phone.value': '+972-76-598-9131',
    'contact.email.label': 'Email',
    'contact.hours.label': 'Hours',
    'contact.hours.value': 'Sun-Fri 09:00-18:00',
    'policies.tagline': 'Clear and fair',
    'policies.title': 'Delivery, cancellation, and privacy policy',
    'policies.subtitle': 'Our policies protect your purchase, respect the law, and safeguard your privacy.',
    'policies.delivery.title': 'Supply policy',
    'policies.delivery.description': 'Delivery within Israel is up to 7 business days; international shipping follows destination timelines (typically 7-14 business days).',
    'policies.cancellation.title': 'Cancellation policy',
    'policies.cancellation.description': 'Orders can be cancelled subject to returning items in new condition and complying with applicable law. Refunds are coordinated after verification.',
    'policies.consumerLaw.title': 'Consumer protection',
    'policies.consumerLaw.description': 'Cancellation terms follow the Israeli Consumer Protection Law, 5741-1981, and all binding regulations.',
    'policies.privacy.title': 'Privacy commitment',
    'policies.privacy.description': "Customer details are secured and won't be shared with third parties except for site operation or legal compliance.",
    'terms.tagline': 'Site terms',
    'terms.title': 'Terms of use and purchase',
    'terms.subtitle': 'Placing an order means you accept our terms, cancellation rules, and privacy notice.',
    'terms.acceptance': 'Confirm before checkout',
    'terms.acceptance.description': 'Before payment we ask for your approval of the terms via checkbox or explicit confirmation on the payment step.',
    'terms.usage': 'Using the site',
    'terms.usage.description': 'Use is intended for purchasing holy books and related items only, according to the guidelines listed here.',
    'terms.policyLink': 'Accessing the terms',
    'terms.policyLink.description': 'The terms are detailed on this page and linked from every footer for easy reference.',
    'cart.terms.checkbox': 'I confirm the site terms',
    'cart.terms.required': 'Please approve the terms before placing your order.',
    'cart.terms.link': 'Read the full terms here',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('he');
  const [currency, setCurrency] = useState<Currency>('ILS');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, setCurrency, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
